#!/bin/bash
#SBATCH -A CS4380_5351_7332 # account name
#SBATCH -J p5_raytrace      # job name
#SBATCH -o p5_raytrace.%j   # name of the output and error file
#SBATCH -N 1                # total number of nodes requested
#SBATCH -n 1                # total number of tasks requested
#SBATCH -p gpu              # queue name
#SBATCH -t 00:01:00         # expected maximum runtime (hh:mm:ss)

date

./raytrace_cuda 2000 128
./raytrace_cuda 2000 256
./raytrace_cuda 4000 128

date
